language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - nightly

matrix:
  allow_failures:
    - php: nightly

install:
    - composer install --prefer-source --no-interaction
    # PHPUnit
    - composer require phpunit/phpunit --dev
    - ./vendor/bin/phpunit --version

before_script: 
    ## Install Code climate reporter
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
    - chmod +x ./cc-test-reporter 
    - ./cc-test-reporter before-build

script: XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    ## Code climate
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
